[package]
name = "zepto"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm = "0.29.0"
dirs = "6.0.0"
ratatui = "0.29.0"
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0.219"
toml = "0.9.2"
